# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster2 config file to be used when cluster2 has been promoted
#               in primary cluster. This config allow you to backup cluster2 in S3.

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster2
spec:
  instances: 3
  imageName: quay.io/enterprisedb/postgresql:14.1
  
  superuserSecret:
    name: superuser-secret

  bootstrap:
     recovery:
       backup:
         name: backup-test
  
  #replica:
  #  enabled: true
  #  source: cluster1

  storage:
    size: 1Gi
    
  backup:
      barmanObjectStore:
        destinationPath: "s3://cnp/"
        endpointURL: "http://192.168.1.16:9000"
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: minio-creds
            key: MINIO_SECRET_KEY
