# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster2 config file from cluster1 backups and WAL's.

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster2
spec:
  instances: 3
  imageName: ###IMAGENAME###
  
  superuserSecret:
    name: superuser-secret

  bootstrap:
     recovery:
       backup:
         name: backup-test
  
  # Log file replication
  # /!\ Comment replica to start cluster in RW
  replica:
    enabled: true
    source: cluster1

  storage:
    size: 1Gi

  externalClusters:
    - name: cluster1
      barmanObjectStore:
        destinationPath: "###S3_DESTINATIONPATH###"
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY
          sessionToken:
            name: aws-creds
            key: ACCESS_SESSION_TOKEN
        wal:
          maxParallel: 8
