# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster1 config file

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster1
spec:
  instances: 3
  imageName: ###IMAGENAME###

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 1Gi

  monitoring:
   enablePodMonitor: true
 
  backup:
    barmanObjectStore:
      destinationPath: "###MINIO_DESTINATIONPATH###"
      endpointURL: "###MINIO_ENDPOINTURL###"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: minio-creds
          key: MINIO_SECRET_KEY
      data:
        immediateCheckpoint: true
    retentionPolicy: "1d"
