# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster2 config file.
#               When apply, this cluster2 restore last backup and WAL's from S3.
#               An streaming replication is installed from cluster1.

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster2
spec:
  instances: 3
  imageName: quay.io/enterprisedb/postgresql:14.1
  
  superuserSecret:
    name: superuser-secret

  bootstrap:
     recovery:
       backup:
         name: backup-test
  
  replica:
    enabled: true
    source: cluster1

  storage:
    size: 1Gi
    
  externalClusters:
  - name: cluster1
    connectionParameters:
      host: cluster1-rw
      user: streaming_replica
    sslKey:
      name: cluster1-replication
      key: tls.key
    sslCert:
      name: cluster1-replication
      key: tls.crt
    sslRootCert:
      name: cluster1-ca
      key: ca.crt
    barmanObjectStore:
        destinationPath: s3://cnp/
        endpointURL: "http://192.168.56.1:9000"
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: minio-creds
            key: MINIO_SECRET_KEY
