# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster2 config file from cluster1 backups and WAL's.

apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster2
spec:
  instances: 3
  imageName: quay.io/enterprisedb/postgresql:14.1
  
  superuserSecret:
    name: superuser-secret

  bootstrap:
     recovery:
       backup:
         name: backup-test
  
  # Log file replication
  # /!\ Comment replica to start cluster in RW
  replica:
    enabled: true
    source: cluster1

  storage:
    size: 1Gi

  externalClusters:
    - name: cluster1
      barmanObjectStore:
        destinationPath: s3://cnp/
        endpointURL: "http://192.168.56.1:9000"
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: minio-creds
            key: MINIO_SECRET_KEY
